### ISSUE TITLE
URLs of analysis phase 1

### ISSUE THREAD

**Issue by iosonosempreio** [densitydesign/atlante-calvino-project#24]
When activating an analysis from the territory the urls doesn't change.

E.g. "Luoghi"

`/atlante-calvino-project/archipelago` > `/atlante-calvino-project/space/phase1`

**Comment by skaffo** [comment]
@iosonosempreio il funzionamento della pagina,partendo da territorio è di cambiare il contenuto in base a se si clicca una delle tre opzioni nebbia/elenchi/luoghi quindi non sono dei veri propri link ma sono dei componenti chiamati <RadioButtonWithClose /> che hanno anche la possibilità di essere chiusi e tornare al territorio. Quindi c'è da capire se è da mantenere questa logica o inserire un normale link.

**Comment by iosonosempreio** [comment]
Non è possibile aggiornare la url quando è selezionata un'analisi?
Il funzionamento generale della pagina è ok a parte la url e non la vorremmo cambiare. Inserire il link che effetto avrebbe?

**Comment by skaffo** [comment]
@iosonosempreio non essendo componenti controllati ho verificato anche con giovanni e per effettuare questo sarebbe da cambiare la logica dei vari componenti.
