### ISSUE TITLE
Multiple selection panel not closing

### ISSUE THREAD

**Issue by iosonosempreio** [densitydesign/atlante-calvino-project#25]
There is no way to close the panel once opened

![Screenshot 2020-11-27 at 19 04 26](https://user-images.githubusercontent.com/7115395/100475463-7430d980-30e3-11eb-9508-13adfa7945f7.png)

**Comment by skaffo** [comment]
@iosonosempreio fixed.

**Comment by skaffo** [comment]
Fixed @iosonosempreio
