### ISSUE TITLE
Modifiche mancanti

### ISSUE THREAD

**Issue by skaffo** [densitydesign/atlante-calvino-project#27]
- [x] Cambiare labels pagina combinare (Esteriore, Interiore, Forma diventano Piano Formale, Piano Interiore, Piano Formale)

- [x] Mettere scritta sopra combinare come da immagine di Angeles (Muovi lo slider per vedere la struttura dei livelli <br /> Clicca icona occhiali per evidenziare la combinazione)

- [x] Trama: quando fai cerca per volumi "Gli amori difficile" vengono fuori solo tre (l'avv. di un fotografo, poeta e sciatore), mancano (l'avv. di un soldato, viaggiatore, impiegato, miope, sposi, moglie, bagnante, lettore; un letto di passaggio; la formica arg; la nuvola di smog; il guidatore notturno). Stesso problema con "I Racconti", vengono fuori solo 29 titoli e sono di piú.

- [x] Indice visivo. Controllare click nell'indice visivo su video guide cambio lingua ecc. (quando sei in qualsiasi viz, torni all'indice visivo e cambi la lingua, torna a la viz precedente). Quando si torna all'indice dalla pagina "istruzioni per l'uso" non [funzionano correttamente i link alle tappe](https://user-images.githubusercontent.com/10846801/104715787-481af780-5727-11eb-9c7a-7c08b1043c8a.mp4) (fenomeno, processo, problema). Stesso caso succede nella pagina "istruzione per l'uso" cliccando su gli itinerari dei dubbio, spazio, forma.

- [x] è possibile aggiungere il switch di lingua IT/EN nel angolo superiore destro quando sei su una delle pagine delle viz orientative (bussola)?

- [x] aggiustare problema di layout in pagina atlante-calvino-project/compass (vedi video sotto)

- [x] landing: da link "video guida" / "video guide" ti porta a pubblicazioni / pubblications @skaffo 
- [x] da istruzione per l'uso a Bussola: deve aprire una nuova finestra; quando premi su una viz non chiude dopo; @skaffo

**Comment by iosonosempreio** [comment]
Ho riaperto il discorso della ricerca su Trama perché anche dopo aver fatto pull con le vostre ultime modifiche non riesco a d aprire il pannello per selezionare ricerca per volumi.

**Comment by skaffo** [comment]
@iosonosempreio prova ora.

**Comment by skaffo** [comment]
@angelesbri1s Slider combinare colorare l'handle component (Colore Blu Calvino) una volta selezionato (Togliere puntino). Se tolgo il puntino come faccio a selezionare? Non posso mettere il click Sul handle component.

**Comment by skaffo** [comment]
@angelesbri1s @iosonosempreio (Indice visivo > con Firefox, i numeri delle tappe vengono a lato sinistra. Riportargli a destra (la bussola copre i numeri) 
La parte delle tappe nell'indice è stato modificato da Tommi e quella parte l'ha seguita lui.

**Comment by skaffo** [comment]
@bea92 @angelesbri1s @iosonosempreio Fixato il bug di combinare. (Bug Combinare cercando un volume cliccando sul rettangolo viene mostrato solo il primo livello e non i livelli successivi.)

**Comment by angelesbri1s** [comment]
@skaffo  Ho riaperto il discorso >> Pagina "Tre itinerari": la "forma" resta troppo in basso rispetto agli altre itinerari (offset anchor point?) Deve venire in alto come gli altri. Ancora vedo il titolo e contenuto della Forma in basso rispetto alla finestra.

**Comment by skaffo** [comment]
@iosonosempreio @angelesbri1s 
Per questo punto: sistemare icone Index Menu: si muovono ancora quando fai hover sul titolo degli approffondimenti
Lo dovrebbe vedere Tommaso in base ai calcoli che fa per posizionare le varie icone.

**Comment by skaffo** [comment]
@angelesbri1s Per questo punto:
Trama: quando fai cerca per volumi "Gli amori difficile" vengono fuori solo tre (l'avv. di un fotografo, poeta e sciatore), mancano (l'avv. di un soldato, viaggiatore, impiegato, miope, sposi, moglie, bagnante, lettore; un letto di passaggio; la formica arg; la nuvola di smog; il guidatore notturno). Stesso problema con "I Racconti", vengono fuori solo 29 titoli e sono di piú.

Ho provato a vedere il dataset per esempio il titolo l'avvocato di un soldato è associato al volume:
Ultimo viene il corvo

Penso ci sia da modificare il dataset in questione: dataset_lines.json

**Comment by angelesbri1s** [comment]
> @angelesbri1s Per questo punto:
> Trama: quando fai cerca per volumi "Gli amori difficile" vengono fuori solo tre (l'avv. di un fotografo, poeta e sciatore), mancano (l'avv. di un soldato, viaggiatore, impiegato, miope, sposi, moglie, bagnante, lettore; un letto di passaggio; la formica arg; la nuvola di smog; il guidatore notturno). Stesso problema con "I Racconti", vengono fuori solo 29 titoli e sono di piú.
> 
> Ho provato a vedere il dataset per esempio il titolo l'avvocato di un soldato è associato al volume:
> Ultimo viene il corvo
> 
> Penso ci sia da modificare il dataset in questione: dataset_lines.json

ok! grazie @skaffo , allora ricontrollo e modifico il dataset_lines.json ;)

**Comment by angelesbri1s** [comment]
> Bussola: quando sei sulle pagine di esplorazione del "tempo dell'opere" oppure "i flussi dei raconti" , cambiare icona indice menu (quella in alto a sinistra) per una "x" che chiude e ti fa tornare alla bussola @skaffo

Grazie @skaffo! ho visto e funziona! volevamo chiederti si è possibile al posto dell'icona "indice" mettere la "x" (e al posto della "x" non mettere niente)?

**Comment by angelesbri1s** [comment]
> @angelesbri1s Per questo punto:
> Trama: quando fai cerca per volumi "Gli amori difficile" vengono fuori solo tre (l'avv. di un fotografo, poeta e sciatore), mancano (l'avv. di un soldato, viaggiatore, impiegato, miope, sposi, moglie, bagnante, lettore; un letto di passaggio; la formica arg; la nuvola di smog; il guidatore notturno). Stesso problema con "I Racconti", vengono fuori solo 29 titoli e sono di piú.
> 
> Ho provato a vedere il dataset per esempio il titolo l'avvocato di un soldato è associato al volume:
> Ultimo viene il corvo
> 
> Penso ci sia da modificare il dataset in questione: dataset_lines.json

@skaffo ho provato a sistemare il dataset questo weekend. Come sappiamo, un titolo può esere parte di più di un volume. Nel "cerca per volume" dovrebbero comparire tutti i titoli associati a un volume cercato.
Ad esempio, il titolo S140 "Il guidatore notturno" compare nei volumi V014, V015, V017, V023. 
Ho notato che quando cercavo il volume V017 "Gli amori difficili" non compare il titolo S140 "Il guidatore notturno"; compare soltanto con la ricerca di "Ti con zero" V014.

Effettivamente, il json non riporta il rapporto tra volume e titoli.
Ho fatto un tentivo di modifica del json di questa viz sensa risultati. 
Questo rapporto è già costruito in questo file (https://github.com/densitydesign/atlante-calvino-project/blob/dev/src/general/TextSearch/volumes.json). Lo stai utilizzando?

**Comment by angelesbri1s** [comment]
> bug: quando sei in qualsiasi viz, torni all'indice visivo e cambi la lingua, torna a la viz precedente @skaffo

Ciao @skaffo! stiamo andando bene con l'inserimento del contenuto in Inglese ;) funziona il tool, è una bomba! Ma abbiamo notato questo bug che ho messo sul elenco di modifiche mancante.

Ciao Matteo
abbiamo riguardato questo bug e abbiamo identificato anche questo caso. Sembrerebbe che ha da fare con la chiusura del menu top nav, perche abbiamo visto che il routing è giusto
https://user-images.githubusercontent.com/10846801/104714336-62ec6c80-5725-11eb-82cf-22a211ce2860.mp4

**Comment by iosonosempreio** [comment]
Ciao @skaffo abbiamo trovato questo problema di layout (media-query?)

https://user-images.githubusercontent.com/7115395/104732933-38f37400-573e-11eb-9933-9e250f91785e.mp4

**Comment by skaffo** [comment]
@iosonosempreio per la bussola si ci sarebbero da fare delle media query in base a come lo volete su ipad o altri dispositivi.

**Comment by skaffo** [comment]
da istruzione per l'uso a Bussola: deve aprire una nuova finestra; quando premi su una viz non chiude dopo; @skaffo in che senso non chiude dopo? @iosonosempreio @angelesbri1s
